### ISSUE TITLE
Path to the LED file is different on my system :(

### ISSUE THREAD

**Issue by Samyak2** [MadhavJivrajani/halp#1]
The path in my system is `/sys/class/leds/input4::capslock/brightness` (4 instead of 3).

Now I can't send an emergency message, pls halp :(

---

(maybe consider looking for `input[0-9]::capslock` inside that directory?)

**Comment by MadhavJivrajani** [comment]
Does it not work even with specifying the path using `--path`? 

The regex might be a good idea

**Comment by Samyak2** [comment]
> Does it not work even with specifying the path using `--path`? 

That does work 😄, but I thought it might be better if it could handle such cases by default (if the pattern is common enough that is, not sure how it's on other systems)

**Comment by MadhavJivrajani** [comment]
Okay so I think that format is pretty [standard](https://www.kernel.org/doc/html/latest/leds/leds-class.html). The approach you suggested should work great! Do you want to take this up?

**Comment by Samyak2** [comment]
Sure!

**Comment by Samyak2** [comment]
Hi! I haven't gotten around to doing it yet. I'll start after #3 is merged since there are major changes.

**Comment by MadhavJivrajani** [comment]
#3 merged
